label define labnum 1 `"CheckBackNextWeekHOTAir"', modify
label define labnum 2 `"CheckBackNextWeekMSNBC"', modify
label define labnum 3 `"CheckBackNextWeekNYT"', modify
label define labnum 4 `"DMediaNYT"', modify
label define labnum 5 `"DOnlyMainMediaABC"', modify
label define labnum 6 `"DOnlyMainMediaCBS"', modify
label define labnum 7 `"DOnlyMainMediaCNN"', modify
label define labnum 8 `"DOnlyMainMediaNBC"', modify
label define labnum 9 `"DOnlyMainMediaNYT"', modify
label define labnum 10 `"JonesEducation"', modify
label define labnum 11 `"JonesExperience"', modify
label define labnum 12 `"JonesFamily"', modify
label define labnum 13 `"JonesReligion"', modify
label define labnum 14 `"RAltMediaFoxNews"', modify
label define labnum 15 `"RAltMediaHotAirBlog"', modify
label define labnum 16 `"RAltMediaHuffPost"', modify
label define labnum 17 `"RAltMediaLatinoSources"', modify
label define labnum 18 `"RCandJonesOnlyMainWebpage"', modify
label define labnum 19 `"RCandWilliamsAllMediaWebpage"', modify
label define labnum 20 `"RCandWilliamsOnlyMainWebpage"', modify
label define labnum 21 `"REndGroupQuestions"', modify
label define labnum 22 `"REndorsementsAllMedia"', modify
label define labnum 23 `"RMediaABCNews"', modify
label define labnum 24 `"RMediaCBSNews"', modify
label define labnum 25 `"RMediaNBCNews"', modify
label define labnum 26 `"RMediaNYT"', modify
label define labnum 27 `"RMediaWSJ"', modify
label define labnum 28 `"RMediaWireServices"', modify
label define labnum 29 `"ROnlyMainMediaABC"', modify
label define labnum 30 `"ROnlyMainMediaNBC"', modify
label define labnum 31 `"ROnlyMainMediaNYT"', modify
label define labnum 32 `"SmithEducation"', modify
label define labnum 33 `"SmithExperience"', modify
label define labnum 34 `"SmithFamily"', modify
label define labnum 35 `"SmithReligion"', modify
label define labnum 36 `"Subject Sign-in"', modify
label define labnum 37 `"Substage2and3BetwIntD&R"', modify
label define labnum 38 `"Substage2and3BetwNoIntD&R"', modify
label define labnum 39 `"That's it for this Week"', modify
label define labnum 40 `"WelcomeWk2D&RImpC"', modify
label define labnum 41 `"WelcomeWk2D&RIntB"', modify
label define labnum 42 `"WelcomeWk2D&RNoIntB"', modify
label define labnum 43 `"WelcomeWk2D&RnotImpC"', modify
label define labnum 44 `"WelcomeWk2DA"', modify
label define labnum 45 `"WelcomeWk2RA"', modify
label define labnum 46 `"Whoops -- Not a Valid Subject ID"', modify
label define labnum 47 `"WilliamsEducation"', modify
label define labnum 48 `"WilliamsExperience"', modify
label define labnum 49 `"WilliamsFamily"', modify
label define labnum 50 `"WilliamsReligion"', modify
label define labnum 51 `"Wilson's WilsonFamily"', modify
label define labnum 52 `"WilsonEducation"', modify
label define labnum 53 `"WilsonExperience"', modify
label define labnum 54 `"WilsonReligion"', modify
label define labnum 55 `"Wk1DSmithBackground"', modify
label define labnum 56 `"Wk1DSmithCandidatePicture"', modify
label define labnum 57 `"Wk1DSmithExperience"', modify
label define labnum 58 `"Wk1DSmithFamily"', modify
label define labnum 59 `"Wk1DSmithPersonality"', modify
label define labnum 60 `"Wk1DSmithSlogan"', modify
label define labnum 61 `"Wk1DWilsonBackground"', modify
label define labnum 62 `"Wk1DWilsonCandidatePicture"', modify
label define labnum 63 `"Wk1DWilsonExperience"', modify
label define labnum 64 `"Wk1DWilsonFamily"', modify
label define labnum 65 `"Wk1DWilsonPersonality"', modify
label define labnum 66 `"Wk1DWilsonSlogan"', modify
label define labnum 67 `"Wk1RJonesBackground"', modify
label define labnum 68 `"Wk1RJonesCandidatePicture"', modify
label define labnum 69 `"Wk1RJonesExperience"', modify
label define labnum 70 `"Wk1RJonesFamily"', modify
label define labnum 71 `"Wk1RJonesPersonality"', modify
label define labnum 72 `"Wk1RWilliamsBackground"', modify
label define labnum 73 `"Wk1RWilliamsCandidatePicture"', modify
label define labnum 74 `"Wk1RWilliamsExperience"', modify
label define labnum 75 `"Wk1RWilliamsFamily"', modify
label define labnum 76 `"Wk1RWilliamsPersonality"', modify
label define labnum 77 `"Wk2DEndorsementAFLCIO"', modify
label define labnum 78 `"Wk2DEndorsementChamberofCommerce"', modify
label define labnum 79 `"Wk2DemCandsRealistic"', modify
label define labnum 80 `"Wk2DemPoll"', modify
label define labnum 81 `"Wk2REndorsemChamberofCommerceEndorsement"', modify
label define labnum 82 `"Wk2REndorsementAFLCIO"', modify
label define labnum 83 `"Wk2RJonesJobs"', modify
label define labnum 84 `"Wk2RWilliamsJobs"', modify
label define labnum 85 `"Wk2RepCandsRealistic"', modify
label define labnum 86 `"Wk2RepPoll"', modify
label define labnum 87 `"wk2DSmithEconPhil"', modify
label define labnum 88 `"wk2DSmithJobs"', modify
label define labnum 89 `"wk2DWilsonEconPhil"', modify
label define labnum 90 `"wk2DWilsonJobs"', modify
label define labnum 91 `"wk2RJonesEconPhil"', modify
label define labnum 92 `"wk2RWilliamsEconPhil"', modify
label define labnum 93 `"wk2d1CBSHUFEcon2"', modify
label define labnum 94 `"wk2d1CNNUNIEcon22"', modify
label define labnum 95 `"wk2d1NBCFOXEcon10"', modify
label define labnum 96 `"wk2d1REUROOTEcon18"', modify
label define labnum 97 `"wk2d2ABCABCEcon37"', modify
label define labnum 98 `"wk2d2APAPEcon42"', modify
label define labnum 99 `"wk2d2NBCNBCEcon62"', modify
label define labnum 100 `"wk2d2NYTNYTEcon54"', modify
label define labnum 101 `"wk2d3CBSHUFEcon2"', modify
label define labnum 102 `"wk2d3CNNUNIEcon22"', modify
label define labnum 103 `"wk2d3NBCFOXEcon10"', modify
label define labnum 104 `"wk2d3REUROOTEcon18"', modify
label define labnum 105 `"wk2r1ABCROOTEcon118"', modify
label define labnum 106 `"wk2r1APFOXEcon126"', modify
label define labnum 107 `"wk2r1NBCUNIEcon122"', modify
label define labnum 108 `"wk2r1WSJHUFEcon110"', modify
label define labnum 109 `"wk2r2APAPEcon78"', modify
label define labnum 110 `"wk2r2CBSCBSEcon66"', modify
label define labnum 111 `"wk2r2REUREUEcon82"', modify
label define labnum 112 `"wk2r2WSJWSJEcon94"', modify
label define labnum 113 `"wk2r3ABCROOTEcon118"', modify
label define labnum 114 `"wk2r3APFOXEcon126"', modify
label define labnum 115 `"wk2r3NBCUNIEcon122"', modify
label define labnum 116 `"wk2r3WSJHUFEcon110"', modify
label define labnum 117 `"wk3DSmithEduc"', modify
label define labnum 118 `"wk3DSmithSocPhil"', modify
label define labnum 119 `"wk3DWilsonEduc"', modify
label define labnum 120 `"wk3DWilsonSocPhil"', modify
label define labnum 121 `"wk3RJonesEduc"', modify
label define labnum 122 `"wk3RJonesSocPhil"', modify
label define labnum 123 `"wk3RWilliamsEduc"', modify
label define labnum 124 `"wk3RWilliamsSocPhil"', modify
label define labnum 125 `"wk4DSmithChina"', modify
label define labnum 126 `"wk4DSmithDefense"', modify
label define labnum 127 `"wk4DWilsonChina"', modify
label define labnum 128 `"wk4DWilsonDefense"', modify
label define labnum 129 `"wk4RJonesChina"', modify
label define labnum 130 `"wk4RJonesDefense"', modify
label define labnum 131 `"wk4RWilliamsChina"', modify
label define labnum 132 `"wk4RWilliamsDefense"', modify
label define labnum 133 `"wk5DSmithAbortion"', modify
label define labnum 134 `"wk5DSmithGay"', modify
label define labnum 135 `"wk5DWilsonAbortion"', modify
label define labnum 136 `"wk5DWilsonGay"', modify
label define labnum 137 `"wk5RJonesAbortion"', modify
label define labnum 138 `"wk5RJonesGay"', modify
label define labnum 139 `"wk5RWilliamsAbortion"', modify
label define labnum 140 `"wk5RWilliamsGay"', modify
label define labnum 141 `"wk6DSmithHealth"', modify
label define labnum 142 `"wk6DSmithTaxes"', modify
label define labnum 143 `"wk6DWilsonHealth"', modify
label define labnum 144 `"wk6DWilsonTaxes"', modify
label define labnum 145 `"wk6RJonesHealth"', modify
label define labnum 146 `"wk6RJonesTaxes"', modify
label define labnum 147 `"wk6RWilliamsHealth"', modify
label define labnum 148 `"wk6RWilliamsTaxes"', modify
label define labnum 149 `"wk7DSmithAffirm"', modify
label define labnum 150 `"wk7DSmithImmigration"', modify
label define labnum 151 `"wk7DWilsonAffirm"', modify
label define labnum 152 `"wk7DWilsonImmigration"', modify
label define labnum 153 `"wk7RJonesAffirm"', modify
label define labnum 154 `"wk7RJonesImmigration"', modify
label define labnum 155 `"wk7RWilliamsAffirm"', modify
label define labnum 156 `"wk7RWilliamsImmigration"', modify
label define labnum 157 `"wk8DSmithAfghan"', modify
label define labnum 158 `"wk8DSmithMil"', modify
label define labnum 159 `"wk8DWilsonAfghan"', modify
label define labnum 160 `"wk8DWilsonMil"', modify
label define labnum 161 `"wk8JRonesAfghan"', modify
label define labnum 162 `"wk8RJonesMil"', modify
label define labnum 163 `"wk8RWilliamsAfghan"', modify
label define labnum 164 `"wk8RWilliamsMil"', modify
label define labnum 165 `"wk9DSmithDeathPen"', modify
label define labnum 166 `"wk9DSmithStemCells"', modify
label define labnum 167 `"wk9DWilsonDeathPen"', modify
label define labnum 168 `"wk9DWilsonStemCells"', modify
label define labnum 169 `"wk9RJonesDeathPen"', modify
label define labnum 170 `"wk9RJonesStemCells"', modify
label define labnum 171 `"wk9RWilliamsDeathPen"', modify
label define labnum 172 `"wk9RWilliamsStemCells"', modify
label define sub 1 `"S1"', modify
label define sub 2 `"S2"', modify
label define sub 3 `"S3"', modify
label define type1 1 `"TOD"', modify
label define type1 2 `"TTO"', modify
label define type1 3 `"VAL"', modify
label define labelnum 1 `"BeginGroup"', modify
label define labelnum 2 `"BeginGroupRepeated"', modify
label define labelnum 3 `"CheckBackNextWeekHOTAir"', modify
label define labelnum 4 `"CheckBackNextWeekMSNBC"', modify
label define labelnum 5 `"CheckBackNextWeekNYT"', modify
label define labelnum 6 `"D01IntDiverseImp"', modify
label define labelnum 7 `"D02IntMainImp"', modify
label define labelnum 8 `"D03NoIntDiverseImp"', modify
label define labelnum 9 `"D04NoIntMainImp"', modify
label define labelnum 10 `"D05IntDiverseNot"', modify
label define labelnum 11 `"D06IntMainNot"', modify
label define labelnum 12 `"D07NoIntDiverseNot"', modify
label define labelnum 13 `"D08NoIntMainNot"', modify
label define labelnum 14 `"DAltMediaAfricanAmericanSources"', modify
label define labelnum 15 `"DAltMediaFoxNews"', modify
label define labelnum 16 `"DAltMediaHotAirBlog"', modify
label define labelnum 17 `"DAltMediaHuffPost"', modify
label define labelnum 18 `"DAltMediaLatinoSources"', modify
label define labelnum 19 `"DAltMediaMSNBCNews"', modify
label define labelnum 20 `"DCandSmithAllMediaWebpage"', modify
label define labelnum 21 `"DCandSmithOnlyMainWebpage"', modify
label define labelnum 22 `"DCandWilsonAllMediaWebpage"', modify
label define labelnum 23 `"DCandWilsonOnlyMainWebpage"', modify
label define labelnum 24 `"DEndGroupQuestions"', modify
label define labelnum 25 `"DEndorsementsAllMedia"', modify
label define labelnum 26 `"DEndorsementsOnlyMain"', modify
label define labelnum 27 `"DMediaABCNews"', modify
label define labelnum 28 `"DMediaCBSNews"', modify
label define labelnum 29 `"DMediaCNNNews"', modify
label define labelnum 30 `"DMediaNBCNews"', modify
label define labelnum 31 `"DMediaNYT"', modify
label define labelnum 32 `"DMediaWSJ"', modify
label define labelnum 33 `"DMediaWireServices"', modify
label define labelnum 34 `"DOnlyMainMediaABC"', modify
label define labelnum 35 `"DOnlyMainMediaCBS"', modify
label define labelnum 36 `"DOnlyMainMediaCNN"', modify
label define labelnum 37 `"DOnlyMainMediaNBC"', modify
label define labelnum 38 `"DOnlyMainMediaNYT"', modify
label define labelnum 39 `"DOnlyMainMediaWSJ"', modify
label define labelnum 40 `"DOnlyMainMediaWireServices"', modify
label define labelnum 41 `"JonesEducation"', modify
label define labelnum 42 `"JonesExperience"', modify
label define labelnum 43 `"JonesFamily"', modify
label define labelnum 44 `"JonesReligion"', modify
label define labelnum 45 `"R09IntDiverseImp"', modify
label define labelnum 46 `"R10IntMainImp"', modify
label define labelnum 47 `"R11NoIntDiverseImp"', modify
label define labelnum 48 `"R12NoIntMainImp"', modify
label define labelnum 49 `"R13IntDiverseNot"', modify
label define labelnum 50 `"R14IntMainNot"', modify
label define labelnum 51 `"R15NoIntDiverseNot"', modify
label define labelnum 52 `"R16NoIntMainNot"', modify
label define labelnum 53 `"RAltMediaAfricanAmericanSources"', modify
label define labelnum 54 `"RAltMediaFoxNews"', modify
label define labelnum 55 `"RAltMediaHotAirBlog"', modify
label define labelnum 56 `"RAltMediaHuffPost"', modify
label define labelnum 57 `"RAltMediaLatinoSources"', modify
label define labelnum 58 `"RCandJonesAllMediaWebpage"', modify
label define labelnum 59 `"RCandJonesOnlyMainWebpage"', modify
label define labelnum 60 `"RCandWilliamsAllMediaWebpage"', modify
label define labelnum 61 `"RCandWilliamsOnlyMainWebpage"', modify
label define labelnum 62 `"REndGroupQuestions"', modify
label define labelnum 63 `"REndorsementsAllMedia"', modify
label define labelnum 64 `"RMediaABCNews"', modify
label define labelnum 65 `"RMediaCBSNews"', modify
label define labelnum 66 `"RMediaNBCNews"', modify
label define labelnum 67 `"RMediaNYT"', modify
label define labelnum 68 `"RMediaWSJ"', modify
label define labelnum 69 `"RMediaWireServices"', modify
label define labelnum 70 `"ROnlyMainMediaABC"', modify
label define labelnum 71 `"ROnlyMainMediaNBC"', modify
label define labelnum 72 `"ROnlyMainMediaNYT"', modify
label define labelnum 73 `"SmithEducation"', modify
label define labelnum 74 `"SmithExperience"', modify
label define labelnum 75 `"SmithFamily"', modify
label define labelnum 76 `"SmithReligion"', modify
label define labelnum 77 `"Subject Sign-in"', modify
label define labelnum 78 `"Substage2and3BetwIntD&R"', modify
label define labelnum 79 `"Substage2and3BetwNoIntD&R"', modify
label define labelnum 80 `"That's it for this Week"', modify
label define labelnum 81 `"WelcomeWk2D&RImpC"', modify
label define labelnum 82 `"WelcomeWk2D&RIntB"', modify
label define labelnum 83 `"WelcomeWk2D&RNoIntB"', modify
label define labelnum 84 `"WelcomeWk2D&RnotImpC"', modify
label define labelnum 85 `"WelcomeWk2DA"', modify
label define labelnum 86 `"WelcomeWk2RA"', modify
label define labelnum 87 `"Whoops -- Not a Valid Subject ID"', modify
label define labelnum 88 `"WilliamsEducation"', modify
label define labelnum 89 `"WilliamsExperience"', modify
label define labelnum 90 `"WilliamsFamily"', modify
label define labelnum 91 `"WilliamsReligion"', modify
label define labelnum 92 `"Wilson's WilsonFamily"', modify
label define labelnum 93 `"WilsonEducation"', modify
label define labelnum 94 `"WilsonExperience"', modify
label define labelnum 95 `"WilsonReligion"', modify
label define labelnum 96 `"Wk1DSmithBackground"', modify
label define labelnum 97 `"Wk1DSmithCandidatePicture"', modify
label define labelnum 98 `"Wk1DSmithExperience"', modify
label define labelnum 99 `"Wk1DSmithFamily"', modify
label define labelnum 100 `"Wk1DSmithPersonality"', modify
label define labelnum 101 `"Wk1DSmithSlogan"', modify
label define labelnum 102 `"Wk1DWilsonBackground"', modify
label define labelnum 103 `"Wk1DWilsonCandidatePicture"', modify
label define labelnum 104 `"Wk1DWilsonExperience"', modify
label define labelnum 105 `"Wk1DWilsonFamily"', modify
label define labelnum 106 `"Wk1DWilsonPersonality"', modify
label define labelnum 107 `"Wk1DWilsonSlogan"', modify
label define labelnum 108 `"Wk1RJonesBackground"', modify
label define labelnum 109 `"Wk1RJonesCandidatePicture"', modify
label define labelnum 110 `"Wk1RJonesExperience"', modify
label define labelnum 111 `"Wk1RJonesFamily"', modify
label define labelnum 112 `"Wk1RJonesPersonality"', modify
label define labelnum 113 `"Wk1RWilliamsBackground"', modify
label define labelnum 114 `"Wk1RWilliamsCandidatePicture"', modify
label define labelnum 115 `"Wk1RWilliamsExperience"', modify
label define labelnum 116 `"Wk1RWilliamsFamily"', modify
label define labelnum 117 `"Wk1RWilliamsPersonality"', modify
label define labelnum 118 `"Wk2DEndorsementAFLCIO"', modify
label define labelnum 119 `"Wk2DEndorsementChamberofCommerce"', modify
label define labelnum 120 `"Wk2DemCandsRealistic"', modify
label define labelnum 121 `"Wk2DemPoll"', modify
label define labelnum 122 `"Wk2REndorsemChamberofCommerceEndorsement"', modify
label define labelnum 123 `"Wk2REndorsementAFLCIO"', modify
label define labelnum 124 `"Wk2RJonesJobs"', modify
label define labelnum 125 `"Wk2RWilliamsJobs"', modify
label define labelnum 126 `"Wk2RepCandsRealistic"', modify
label define labelnum 127 `"Wk2RepPoll"', modify
label define labelnum 128 `"wk2DSmithEconPhil"', modify
label define labelnum 129 `"wk2DSmithJobs"', modify
label define labelnum 130 `"wk2DWilsonEconPhil"', modify
label define labelnum 131 `"wk2DWilsonJobs"', modify
label define labelnum 132 `"wk2RJonesEconPhil"', modify
label define labelnum 133 `"wk2RWilliamsEconPhil"', modify
label define labelnum 134 `"wk2d1CBSHUFEcon2"', modify
label define labelnum 135 `"wk2d1CNNUNIEcon22"', modify
label define labelnum 136 `"wk2d1NBCFOXEcon10"', modify
label define labelnum 137 `"wk2d1REUROOTEcon18"', modify
label define labelnum 138 `"wk2d2ABCABCEcon37"', modify
label define labelnum 139 `"wk2d2APAPEcon42"', modify
label define labelnum 140 `"wk2d2NBCNBCEcon62"', modify
label define labelnum 141 `"wk2d2NYTNYTEcon54"', modify
label define labelnum 142 `"wk2d3CBSHUFEcon2"', modify
label define labelnum 143 `"wk2d3CNNUNIEcon22"', modify
label define labelnum 144 `"wk2d3NBCFOXEcon10"', modify
label define labelnum 145 `"wk2d3REUROOTEcon18"', modify
label define labelnum 146 `"wk2r1ABCROOTEcon118"', modify
label define labelnum 147 `"wk2r1APFOXEcon126"', modify
label define labelnum 148 `"wk2r1NBCUNIEcon122"', modify
label define labelnum 149 `"wk2r1WSJHUFEcon110"', modify
label define labelnum 150 `"wk2r2APAPEcon78"', modify
label define labelnum 151 `"wk2r2CBSCBSEcon66"', modify
label define labelnum 152 `"wk2r2REUREUEcon82"', modify
label define labelnum 153 `"wk2r2WSJWSJEcon94"', modify
label define labelnum 154 `"wk2r3ABCROOTEcon118"', modify
label define labelnum 155 `"wk2r3APFOXEcon126"', modify
label define labelnum 156 `"wk2r3NBCUNIEcon122"', modify
label define labelnum 157 `"wk2r3WSJHUFEcon110"', modify
label define labelnum 158 `"wk3DSmithEduc"', modify
label define labelnum 159 `"wk3DSmithSocPhil"', modify
label define labelnum 160 `"wk3DWilsonEduc"', modify
label define labelnum 161 `"wk3DWilsonSocPhil"', modify
label define labelnum 162 `"wk3RJonesEduc"', modify
label define labelnum 163 `"wk3RJonesSocPhil"', modify
label define labelnum 164 `"wk3RWilliamsEduc"', modify
label define labelnum 165 `"wk3RWilliamsSocPhil"', modify
label define labelnum 166 `"wk4DSmithChina"', modify
label define labelnum 167 `"wk4DSmithDefense"', modify
label define labelnum 168 `"wk4DWilsonChina"', modify
label define labelnum 169 `"wk4DWilsonDefense"', modify
label define labelnum 170 `"wk4RJonesChina"', modify
label define labelnum 171 `"wk4RJonesDefense"', modify
label define labelnum 172 `"wk4RWilliamsChina"', modify
label define labelnum 173 `"wk4RWilliamsDefense"', modify
label define labelnum 174 `"wk5DSmithAbortion"', modify
label define labelnum 175 `"wk5DSmithGay"', modify
label define labelnum 176 `"wk5DWilsonAbortion"', modify
label define labelnum 177 `"wk5DWilsonGay"', modify
label define labelnum 178 `"wk5RJonesAbortion"', modify
label define labelnum 179 `"wk5RJonesGay"', modify
label define labelnum 180 `"wk5RWilliamsAbortion"', modify
label define labelnum 181 `"wk5RWilliamsGay"', modify
label define labelnum 182 `"wk6DSmithHealth"', modify
label define labelnum 183 `"wk6DSmithTaxes"', modify
label define labelnum 184 `"wk6DWilsonHealth"', modify
label define labelnum 185 `"wk6DWilsonTaxes"', modify
label define labelnum 186 `"wk6RJonesHealth"', modify
label define labelnum 187 `"wk6RJonesTaxes"', modify
label define labelnum 188 `"wk6RWilliamsHealth"', modify
label define labelnum 189 `"wk6RWilliamsTaxes"', modify
label define labelnum 190 `"wk7DSmithAffirm"', modify
label define labelnum 191 `"wk7DSmithImmigration"', modify
label define labelnum 192 `"wk7DWilsonAffirm"', modify
label define labelnum 193 `"wk7DWilsonImmigration"', modify
label define labelnum 194 `"wk7RJonesAffirm"', modify
label define labelnum 195 `"wk7RJonesImmigration"', modify
label define labelnum 196 `"wk7RWilliamsAffirm"', modify
label define labelnum 197 `"wk7RWilliamsImmigration"', modify
label define labelnum 198 `"wk8DSmithAfghan"', modify
label define labelnum 199 `"wk8DSmithMil"', modify
label define labelnum 200 `"wk8DWilsonAfghan"', modify
label define labelnum 201 `"wk8DWilsonMil"', modify
label define labelnum 202 `"wk8JRonesAfghan"', modify
label define labelnum 203 `"wk8RJonesMil"', modify
label define labelnum 204 `"wk8RWilliamsAfghan"', modify
label define labelnum 205 `"wk8RWilliamsMil"', modify
label define labelnum 206 `"wk9DSmithDeathPen"', modify
label define labelnum 207 `"wk9DSmithStemCells"', modify
label define labelnum 208 `"wk9DWilsonDeathPen"', modify
label define labelnum 209 `"wk9DWilsonStemCells"', modify
label define labelnum 210 `"wk9RJonesDeathPen"', modify
label define labelnum 211 `"wk9RJonesStemCells"', modify
label define labelnum 212 `"wk9RWilliamsDeathPen"', modify
label define labelnum 213 `"wk9RWilliamsStemCells"', modify
label define type2 1 `"DUR"', modify
label define type2 2 `"FOD"', modify
label define type2 3 `"GRP"', modify
label define type2 4 `"TOD"', modify
label define type2 5 `"TTO"', modify
label define type2 6 `"VAL"', modify
label define type2 7 `"WOR"', modify
label define type4 1 `"COD"', modify
label define type4 2 `"CTO"', modify
label define sub1 1 `"S1"', modify
label define sub1 2 `"S2"', modify
label define sub1 3 `"S3"', modify
label define sub1 4 `"S4"', modify
